// Code generated by MockGen. DO NOT EDIT.
// Source: token_inspector.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"
	time "time"

	jwt "github.com/golang-jwt/jwt"
	gomock "github.com/golang/mock/gomock"
)

// MockTokenInspectorer is a mock of TokenInspectorer interface.
type MockTokenInspectorer struct {
	ctrl     *gomock.Controller
	recorder *MockTokenInspectorerMockRecorder
}

// MockTokenInspectorerMockRecorder is the mock recorder for MockTokenInspectorer.
type MockTokenInspectorerMockRecorder struct {
	mock *MockTokenInspectorer
}

// NewMockTokenInspectorer creates a new mock instance.
func NewMockTokenInspectorer(ctrl *gomock.Controller) *MockTokenInspectorer {
	mock := &MockTokenInspectorer{ctrl: ctrl}
	mock.recorder = &MockTokenInspectorerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenInspectorer) EXPECT() *MockTokenInspectorerMockRecorder {
	return m.recorder
}

// GetEmailFromToken mocks base method.
func (m *MockTokenInspectorer) GetEmailFromToken(token *jwt.Token) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailFromToken", token)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailFromToken indicates an expected call of GetEmailFromToken.
func (mr *MockTokenInspectorerMockRecorder) GetEmailFromToken(token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailFromToken", reflect.TypeOf((*MockTokenInspectorer)(nil).GetEmailFromToken), token)
}

// GetExpiryFromToken mocks base method.
func (m *MockTokenInspectorer) GetExpiryFromToken(token *jwt.Token) (*time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExpiryFromToken", token)
	ret0, _ := ret[0].(*time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExpiryFromToken indicates an expected call of GetExpiryFromToken.
func (mr *MockTokenInspectorerMockRecorder) GetExpiryFromToken(token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExpiryFromToken", reflect.TypeOf((*MockTokenInspectorer)(nil).GetExpiryFromToken), token)
}

// GetTypeFromToken mocks base method.
func (m *MockTokenInspectorer) GetTypeFromToken(token *jwt.Token) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTypeFromToken", token)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTypeFromToken indicates an expected call of GetTypeFromToken.
func (mr *MockTokenInspectorerMockRecorder) GetTypeFromToken(token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTypeFromToken", reflect.TypeOf((*MockTokenInspectorer)(nil).GetTypeFromToken), token)
}
